# Example usage of halo_trace 

First, to import the relevant packages

In [6]:
!ls

build  example2.ipynb  halo_trace	    README.md
dist   example.ipynb   halo_trace.egg-info  setup.py


In [1]:
import os
os.chdir('/home/selvani/MAP/pynbody/halo_trace')
# !pip install -e .

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import halo_trace as ht
import pandas as pd 

%matplotlib inline

A bit about the tracing code:

The tracing code is fairly slow, but should be robust. By default it will cross check steps, meaning it calculates the main progenitor both 1 and 2 steps apart, to make sure they match. If it loses a main progenitor, it can also pick it up again in some cases. Because this process is so slow, usually what you want to do is run it once and save the output, then read in the output for all subsequent uses. Main progenitors are identified by maximizing a merit function (as in AHF's merger tree code), where the merit function of halo

\begin{equation}
\max_j\left(M_{ij} = \frac{N_{i \cap j}}{N_i N_j}\right),
\end{equation}

where $N_i$ and $N_j$ are the number of particles in halos in steps $i$ and $j$, N$_{i \cap j}$ is the number of shared particles. The merit function is maximized in both directions (step 1 to 2 and step 2 to 1), and a match is recorded only if the identified halos match.

Anyway...

The code traces halos and returns a pandas dataframe identifying the main progenitor at each step.

The only mandatory argument in the trace is `sim_base`, which is the path to the directory holding all your simulation time steps. You can specify a file name for the saved trace using `save_file`. You can trace specific halos by spcifying `grplist` (e.g., `grplist=[1, 3, 6]` will trace halos 1, 3, and 6 back), or you can trace all halos above some particle threshold. For all arguments, you can run `ht.tracing.trace_halos?`. So, if want to trace all halos with more than 1000 particles at z=0, no earlier than step 400, then this would run the trace (replacing `sim_base` with your own path):

## Trace

In [3]:
sim_base = '/home/selvani/MAP/Sims/cptmarvel.cosmo25cmb/cptmarvel.cosmo25cmb.4096g5HbwK1BH/snapshots_200crit_cptmarvel'
sim_base = '/home/selvani/MAP/Sims/cptmarvel.cosmo25cmb/cptmarvel.cosmo25cmb.4096g5HbwK1BH/'
# ahf_dir = '.'
ahf_dir = 'ahf_200'

In [4]:
# Test both simulation files AND halo catalogs comprehensively
# working_steps = ht.tracing.test_halo_catalogs_comprehensive(sim_base=sim_base, ahf_dir=ahf_dir)

In [5]:
# working_steps = ht.tracing.test_halo_catalogs(sim_base=sim_base, ahf_dir=ahf_dir)


In [6]:
# sim_base = '/home/selvani/MAP/Sims/cptmarvel.cosmo25cmb/cptmarvel.cosmo25cmb.4096g5HbwK1BH/snapshots_200crit_cptmarvel'
sim_base = '/home/selvani/MAP/Sims/cptmarvel.cosmo25cmb/cptmarvel.cosmo25cmb.4096g5HbwK1BH/'
# ahf_dir = None
ahf_dir = 'ahf_200'
# grplist = None
grplist = np.array([1, 2, 3, 5, 6, 7, 8, 10, 11, 13, 16])

In [7]:
trace = ht.tracing.trace_halos(sim_base=sim_base, 
                               ahf_dir=ahf_dir, 
                               grplist=grplist,
                               min_ntot=500)

cptmarvel.cosmo25cmb.4096g5HbwK1BH.000113 does not exist or has incorrect permissions
45
Using only the following steps which contain ahf_dir and AHF catalogs:
['004096', '003968', '003840', '003712', '003636', '003584', '003456', '003328', '003245', '003200', '003072', '002944', '002816', '002688', '002624', '002560', '002432', '002304', '002176', '002162', '002048', '001920', '001813', '001792', '001664', '001543', '001536', '001408', '001331', '001280', '001162', '001152', '000896', '000818', '000768', '000672', '000640', '000512', '000482', '000291', '000199', '000146', '000128']
File will be saved as /home/selvani/MAP/Sims/cptmarvel.cosmo25cmb/cptmarvel.cosmo25cmb.4096g5HbwK1BH/cptmarvel.cosmo25cmb.4096g5HbwK1BH.004096/cptmarvel.cosmo25cmb.4096g5HbwK1BH.004096.trace_back.hdf5
grplist= [ 1  2  3  5  6  7  8 10 11 13 16]
simlow= /home/selvani/MAP/Sims/cptmarvel.cosmo25cmb/cptmarvel.cosmo25cmb.4096g5HbwK1BH/cptmarvel.cosmo25cmb.4096g5HbwK1BH.004096/cptmarvel.cosmo25cmb.4096g5HbwK1BH.

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
24
[[2050082       0       0 ...       0       0       0]
 [      0 1192571       0 ...       0       0       0]
 [      0       0 1032115 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...   11812       0       0]]
	Ni= [2050082 1194636 1050839  382111 1010570  812761  673607  197867  324491
  471202  303788  281778  243754  180905  176030  143766  154418  108439
   60081   90346   66408   60651   56398   54886   49526   52558   47934
   45997   39436   46347   45555   42642   43871   37445   40983   38459
   21569   41420   38289   41866   41971   35199   33824   38617   32938
   22922   33058   28438   31100   28533   27005   19292   24359   27360
   23869   22983   20809   22158   21417   20506   19167   20758   20203
   18873   16987   17870   16621   18496   16803   14925   17275   15452
   17545   16820   17356   17025   157

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
24
[[2090404       0       0 ...       0       0       0]
 [      0 1255590       0 ...       0       0       0]
 [      0       0 1070682 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0   12400]
 [      0       0       0 ...       0       0       0]]
	Ni= [2090404 1258039 1075987  413124 1027340  815899  694813  205806  340401
  483828  355409  282279  248852  191476  187028  147439  155493   89900
   96194   67428   62817   58067   55516   49422   53287   49271   46439
   47319   47011   47404   46208   45085   40649   43159   38935   41604
   22994   41933   40037   42140   42052   37698   35160   38797   38969
   33184   33451   31654   28500   17078   25538   27932   28850   23708
   24824   24280   23441   23874   22768   21874   20927   19918   20839
   21140   20783   19552   19307   19013   18327   17179   18688   18727
   17416   17274   15173   17451   176

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
24
[[2040088       0       0 ...       0       0       0]
 [      0 1219058       0 ...       0       0       0]
 [      0       0 1029436 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0   12593]]
	Ni= [2040088 1223348 1038793  381509 1007427  788370  672378  197361  330156
  474570  348850  266781  242686  182955  180120  143497  152781   86642
   94092   65673   60223   56981   54735   47828   52534   47673   44288
   46770   46453   47269   45576   44994   36383   42279   37677   40852
   22105   41407   38674   41792   42338   36842   34022   38003   38534
   32592   32895   31089   27116   13042   25154   27289   28442   22745
   24536   23840   22560   23742   22321   21404   19642   19317   20490
   21032   20701   19471   19226   18769   17900   16675   18467   18722
   16947   16929   14486   17207   175

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
24
[[2119883       0       0 ...       0       0       0]
 [      0 1303955       0 ...       0       0       0]
 [      0       0 1092570 ...       0       0       0]
 ...
 [      0       0       0 ...   13000       0       0]
 [      0       0       0 ...       0   12920       0]
 [      0       0       0 ...       0       0   12811]]
	Ni= [2119883 1305421 1093871  442152 1035644  816704  708382  350956  210445
  487793  419275  273851  251864  195673  191668  148028  156051   85165
   67989   56848   60989   59023   49743   57443   55861   53528   51597
   49932   48241   46113   48014   47333   46452   43478   23819   42030
   39160   42159   42350   34961   38478   39734   40692   35233   39348
   39071   33658   33444   30693   31845   28423   28662   29033   23436
   25487   23258   24481   22834   22209   21770   20636   19944   20897
   21120   20724   20432   20290   19373   17579   18717   18430   17576
   17701   17409   17717   17632   171

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
24
[[2032048       0       0 ...       0       0       0]
 [      0 1232090       0 ...       0       0       0]
 [      0       0 1023828 ...       0       0       0]
 ...
 [      0       0       0 ...       0   12708       0]
 [      0       0       0 ...       0       0   12624]
 [      0       0       0 ...       0       0       0]]
	Ni= [2032480 1234131 1026827  393158 1000724  771661  678696  332239  196960
  470913  349754  254306  241418  182595  173847  140466  151256   80399
   65249   58837   61982   56859   47232   57605   54433   52213   50088
   47631   46993   43039   47622   46300   45374   41964   22262   40729
   37192   41191   41828   31417   35942   37095   38066   32953   37964
   38250   32610   32359   27520   30729   27081   27019   28291   22142
   24969   22498   23679   21874   21255   21590   19423   18535   20166
   20908   20751   20421   20130   18820   16698   18323   17691   16533
   17093   16482   17584   17168   167

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
24
[[2051793       0       0 ...       0       0       0]
 [      0 1228863       0 ...       0       0       0]
 [      0       0 1026764 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [2052452 1229985 1030444  420479 1001825  774227  702796  336957  200953
  465673  328811  260365  243505  187349  171468  139988  150758   80029
   73093   65716   60759   56688   56189   46685   54594   52469   50144
   45049   47921   51017   46641   46231   45211   41999   22255   40894
   41920   36376   30324   41062   37278   38119   38219   38456   32835
   38357   32581   32574   28913   30603   27207   26950   28371   25531
   21089   23141   23796   21825   22677   22002   21113   21438   19814
   21051   20055   18611   18765   17885   19463   16940   18370   17336
   17778   17591   16199   17195   168

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
24
[[1993435       0       0 ...       0       0       0]
 [      0 1168453       0 ...       0       0       0]
 [      0       0  984771 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [1994492 1181755  993882  388186  978356  746112  680429  324623  191894
  453958  322394  248170  236081  174425  160653  135420  147650   77293
   73856   64131   57776   55164   57381   45044   53675   51597   48982
   42642   46360   50933   45037   45500   44393   41046   21070   39956
   41548   34252   28452   40445   35608   35108   36179   37604   31512
   37851   31822   31841   27638   29819   26328   25515   27895   25076
   19406   22809   23328   21287   22635   21636   20576   21212   18789
   20870   19683   17998   18385   17068   19463   16419   18120   16868
   17273   17453   15579   16905   164

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


ahf_basename= /home/selvani/MAP/Sims/cptmarvel.cosmo25cmb/cptmarvel.cosmo25cmb.4096g5HbwK1BH/cptmarvel.cosmo25cmb.4096g5HbwK1BH.003200/ahf_200/cptmarvel.cosmo25cmb.4096g5HbwK1BH.003200.0000.z0.266.AHF_
	Matching halos by merit function
24
[[2093260       0       0 ...       0       0       0]
 [      0 1213851       0 ...       0       0       0]
 [      0       0 1048855 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0   13037       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [2093681 1226007 1050525  454590 1008373  786219  704641  340600  207707
  457351  325229  273263  246188  185270  159613  142073  148150  151036
   80478   73479   64785   67424   62691   56631   55264   46646   49012
   53067   48996   50211   45499   46392   45219   42532   41619   38875
   42122   22489   41207   39119   38096   38289   34712   33370   38644
   36208   31328   28687   32909   32951   28901   3079

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
24
[[1997103       0       0 ...       0       0       0]
 [      0 1118625       0 ...       0       0       0]
 [      0       0  987481 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [1998981 1139696  989452  394258  971170  738575  668747  321015  192155
  435141  312735  249627  234518  166692  149555  135116  135795  146318
   75998   73468   59762   64832   62381   54166   53755   44003   45687
   51618   46243   48737   43985   45273   43982   41029   40162   34770
   41511   20678   40159   37540   35340   35095   32137   31314   37848
   35990   27089   26599   31796   31763   26028   29580   25960   27703
   25176   23272   25623   24356   23222   17949   22457   21442   20840
   20575   19205   21142   21024   19618   18953   17214   18023   16325
   18027   16483   17125   17368   169

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
24
[[2006888       0       0 ...       0       0       0]
 [      0 1103053       0 ...       0       0       0]
 [      0       0  980945 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0   11740]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [2008295 1105034  987704  411133  970217  736858  671354  317629  189918
  427127  314702  244913  234037  152914   97893  137115  145788  145609
   94710   75519   65817   58924   53570   53757   55323   44205   51375
   46104   46370   49347   47082   45210   32562   43792   43442   35644
   40428   35216   41064   41511   37085   40091   20801   37938   31759
   35056   31885   31274   31996   32914   29558   25941   26409   24841
   25877   27773   24859   26652   22658   25810   23358   23094   19471
   21093   20038   20697   21204   17907   19673   20130   16492   16274
   17861   17992   16293   17085   173

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
24
[[1902690       0       0 ...       0       0       0]
 [      0 1037806       0 ...       0       0       0]
 [      0       0  885612 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0   11048]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [1910011 1041497  912315  359722  927645  688342  631955  296603  173276
  408984  295736  219054  222147  141729  100313  129515  140637  139756
   91399   71427   62627   52113   51182   51897   55390   42012   49604
   38686   43400   44432   46289   43984   23896   42523   42128   32703
   38726   32337   39339   40803   35201   39096   19202   37028   29708
   32535   30553   29551   30921   32911   28247   23736   22630   23230
   24418   26922   23998   26385   21516   25724   22529   22327   18794
   20342   11885   19696   20976       0   19016   20174   13700   15216
   17278   17537   15654   16225   171

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
21
[[1942339       0       0 ...       0       0       0]
 [      0 1065306       0 ...       0       0       0]
 [      0       0  849503 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0   12603]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [1943488 1065851  853145  354296  941367  718714  618926  299737  181230
  419336  292754  240809  226430  134492  141938   96377  140839  139125
   92499   86034   73736   63638   50563   52215   51611   52719   43099
   49997   43859   44633   34498   44288   42887   42089   40612   39623
   40996   33046   30412   39461   35380   20089   30940   37378   35298
   31911   31013   30233   21752   28489   22697   23661   24939   27507
   27512   26587   21051   24326   24194   22960   22877   21510   21330
   21340   14272   19953   19462   12446   18220   17682   17634   17476
   17377   17040   16413   16170   172

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
21
[[1880837       0       0 ...       0       0    8529]
 [      0 1031167       0 ...       0       0       0]
 [      0       0  815190 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [1890880 1034908  819809  321254  918196  695569  600823  285575  173921
  410696  283385  231053  220254  130431  138954   96254  137032  134482
   90391   84422   71729   61626   48815   51235   50510   52718   42056
   49092   37399   42611   32649   43600   42253   41399   39578   38734
   40610   31542   26582   38950   34532   19038   29728   36873   34015
   31241   30138   29286   17301   27878   21000   22686   23998   27105
   27147   26397   20435   23910   23816   22403   22355   21102   21015
   21188       0   19362   19078   11417   18179   17553   17393   17900
   17065   16650   16043   15723   170

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
21
[[1925653       0       0 ...       0       0       0]
 [      0 1064387       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0   13625]
 [      0       0       0 ...       0       0       0]
 [     38       0       0 ...       0       0       0]]
	Ni= [1925948 1068199  815295  944445  323334  736840  560244  293226  185025
  428768  285778  204428  225061  136457  141678  146588  134523  100820
   81419   92531   89378   74774   63231   49069   56394   52080   51924
   34133   50103   43822   44099   45900   44141   42778   41933   41270
   39759   40958   39478   33096   36814   31933   37223   19607   35402
   32287   26043   31117   31781   30313   28437   28039   27674   24862
   26802   21711   24646   22321   24455   20621   22738   21806   22678
   21497   21359   18102   19827   14271   19621   15644   19067   17422
   18624   17804   17680   17394   172

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
21
[[1810303       0       0 ...     495       0       0]
 [      0  986699       0 ...       0       0       0]
 [      0       0  762700 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...   13375       0       0]]
	Ni= [1811029  991684  764418  898454  269430  689269  524529  269217  169179
  409208  264374  137020  211780  127017  134916  135838  125584   95192
   77852   88299   85834   70690   58858   42518   56392   50104   49538
   33100   48087   41806   41072   45730   42455   41333   40406   39310
   37631   40132   38319   30141   33275   29335   36201   17326   33744
   29249   19935   29562   30015   28511   27082   27228   26645   22863
   26512   19510   23742   20514   23741   18717   21544   20045   21497
   21232   20720   15972   18730   12721   18667   16725   18836   15836
   18515   17303   16984   15412   166

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
21
[[1814498       0       0 ...       0       0       0]
 [      0  973843       0 ...       0       0       0]
 [      0       0  765259 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [1814641  974035  766231  902446  707822  262572  514547  274465  171536
  416130  260507   38965  209610  127499  133561  133666  122541   94082
   87068   87372   73687   71048   64490   57954   58838   49834   49561
   41955   42521   48135   40325   32054   42176   41095   40159   39343
   40152   37301   37837   33835   35931   30453   34141   29024   16978
   29129   29877   29787   28314   27157   16458   27862   13591   26588
   27459   22637   24153   20564   23645   17939   21212   19653   21494
   18144   19757   21818   20969   17902   20536   20146   18724   19550
       0   18342   18995   17456   162

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
21
[[1688617       0       0 ...       0       0       0]
 [      0  905595       0 ...       0       0       0]
 [      0       0  703029 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0   11096]
 [      0       0       0 ...       0       0       0]]
	Ni= [1688994  905844  711797  853277  654812  226895  480936  258497  154408
  393097  243538  142976  195685  116475  126782  121795  114909   88725
   82174   83476   69903   66276   61113   53449   58871   47712   47592
   36572   40718   45982   37311   31463   40371   39413   38640   37069
   39243   35180   36433   29605   34715   27184   32190   26125   15149
   26534   28068   28436   26198   25695   14979   26734   26079   25529
   27391   20450   23109   18957   22755   15621    3564   18496   20516
   15586   18357   21623   19778   16280   19753   19681   17704   19738
   11169   17229   18937   16740   149

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
21
[[1840863       0       0 ...       0       0       0]
 [      0  988657       0 ...       0       0       0]
 [      0       0  776467 ...       0       0       0]
 ...
 [      0       0       0 ...   13412       0       0]
 [      0       0       0 ...       0   13464       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [1840910  988657  777722  915733  738271  293987  512447  294451  426768
  174663  264797  220537  210262  129934  135974  130709  124440   95522
   91771   87466   75115   71043   68321   58780   52396   39631   51010
   43987   48398   42378   43499   42526   41539   40415   40475   19409
   39536   37804   37526   36078   34115   33404   29985   18054   33524
   28401   32848   30237   29748   30032   29174   28581   24626   26544
   24996   26758   24673   23150   23483   23767   23254   22077   21931
   21119   20616   20120   19681   19912   17459   19614   19331   19158
   17923   17259   17635   18056   178

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
21
[[1677184       0       0 ...       0    3599       0]
 [      0  920333       0 ...       0       0       0]
 [      0       0  690278 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [1712091  920651  718414  863645  673965  252744  478664  275124  404026
  156231  248441  126210  197017  118635  128122  117454  117750   90000
   86911   82552   71069   64727   64825   54761   48790   14679   48705
   41520   46249   39159   38774   40750   39628   39530   38739   17004
   37250   35714   36220   34936   32211   28617   26596   16378   32999
   25328   32505   27025   27577   28760   27773   26375   17511   24660
   19811   25530   23502   20673   23058   22866   22699   21628   20843
   19984   19800   19579   18313   19763   15219   18604   17597   18109
   16924   15247   15705   17117   170

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
19
[[1584284       0       0 ...       0       0       0]
 [      0  892954       0 ...       0       0       0]
 [      0       0  596652 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [     74       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [1591949  893724  665996  829016  621370  232469  463344  274540  390974
  148083  244282  192015  113505  123909  119429  116371  106916   88085
   85252   82017   69630   63230   63565   56465   47538   49078   25268
   40084   45018   38266   37550   39667   32749   38720   16355   39090
   37882   26750   36560   35093   35989   34547   34626   30956   31986
   15930   24562   25099   23281   26477   28069   27482   23986   25223
   23393   24802   16898   22929   19253       0   23328   22856   22499
   19066   20422   18494   20765   19363   19319   16669   17935   17433
   16600   18231   14121   12702      

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
19
[[1473990       0       0 ...       0       0       0]
 [      0  823850       0 ...       0       0       0]
 [      0       0  513543 ...       0       0       0]
 ...
 [      0       0       0 ...   12892       0       0]
 [     75       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [1484106  828482  620030  769915  575833  195304  426655  243276  367173
  131325  224847  180311  102427  116245  112647  113902  100675   82209
   80404   77985   65651   53464   59585   51133   44704   47100   25268
   38333   42907   34226   32871   37696   19426   36710   14190   38165
   36470   28082   34688   33046   35068   33108   33489   28813   33272
   13810   21869   22641   19583   24467   26696   25795   21081   22806
   22254   23802       0   22180   16952       0   21754   22357   21612
   17777   19256   16573   20750   18609   19182   15593   17023   16138
   15601   18297   12258   14771   146

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
21
[[1578657       0       0 ...       0       0       0]
 [      0  880175       0 ...       0       0       0]
 [      0       0  613076 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...   14115       0       0]]
	Ni= [1579080  883508  620309  811604  600293  468330  212492  387255  225987
  148805  245196  196160  130988  116400  145151  123996  124166  107723
   92064   87669   86530   54850   63675   70636   62121   64332   51240
   47512   45396   40497   35774   38066   41120   40253   38335   32344
   39366   38794   38378   37654   35546   34958   33877   31389   15402
   31216   30129   16087   26096   26802   28507   27767   27348   25270
   23131   24538   24834   23834   23166   23947   20777   16054   23498
   23318   22993   22733   18137   18835   20577   20716   20675   19813
   19425   16856   17995   18393   184

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
21
[[1416119       0       0 ...       0       0       0]
 [      0  785079       0 ...       0       0       0]
 [      0       0  562674 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0   13668]]
	Ni= [1418753  792293  566245  740459  538097  431299  178357  357613  188032
  131632  219768  180343  130301  102122  134245  114087  113285  100302
   70106   78685   80074   65861   60317   64391   55527   58765   45909
   41779   42752   37842   31907   30513   40072   37899   35654   18828
   38136   37583   36054   35398   32463   33533   31862   29078   11738
   26020   27336   13405   20479   24038   28399   25252   25031   22398
   19640   21688   23458   20307   16924   23082   17560   17729   22137
   22081   22244   21435   15822   17416   18951   20490   20351   18844
   18252   15687   17048   17125   181

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
19
[[1341763       0       0 ...       0       0       0]
 [      0  747397       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0   13259]
 [      0       0       0 ...       0   13695       0]]
	Ni= [1346110  747934  464903  716548  526180  406666  161417  354126  130958
  167357  211310  175094  105292  121076  109107  108094   80537  104857
   75818   78209   73976   52673   62173   56799   48722   43849   44174
   39672   42295   42202   39796   30292   36594   38048   37668   34808
   35310   35435   28857   33458   29689   31079   33055   31518   24151
   27798   13510   26631   22666   24059   11121   24630   16440   22179
   16486   23815   22920   17221   22717   19980   20867   21554   22547
   17141   21292   21974   17515   20421   21276   19816   18283   19490
   18534   20017   18136    9210   167

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
19
[[1333037       0       0 ...       0       0       0]
 [      0  742797       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0   13207]
 [      0       0       0 ...       0   13670       0]]
	Ni= [1337691  743360  463503  712924  522993  403797  159730  351959  129867
  166341  209844  173892  104662  118892  108591  107383   80539  104522
   75425   77754   73470   62231   61454   56480   48310   43409   44047
   39487   42136   42149   39695   30207   36425   37891   37553   34682
   35219   35371   28635   33335   29508   30922   32955   31400   23410
   27683   13341   26292   22508   23763   10872   24517   16122   21982
   16404   23623   22820   17014   22652   19784   20697   21504   22576
   17033   21223   21940   17291   20398   21276   19727   18153   19444
   18454   20017   18088   13864   166

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
21
[[1155555       0       0 ...       0       0       0]
 [      0  674408       0 ...       0       0       0]
 [      0       0  639959 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [1160119  676558  642538  459077  314688  336816  321015  135343  110125
  180610  123887  169910  154776   89041   90776  102448   94050   96586
   79381   69097   65791   50960   50900   40845   31689   43925   39914
   38277   39097   35256   37536   33622   33376   31551   35745   32673
   37693   30056   32011   30023   30805   29746   23661   14267   27098
   23727   26738   24498   10575   25511   23274   19282   22265   21473
   22709   22406   18556   23264   21654   22058   21199   23494   19260
    7640   17999   11737   19829   19941       0   15798   18127   13518
   16713   18280   17739   16448   141

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
21
[[1230935       0       0 ...       0       0       0]
 [      0  662032       0 ...     194       0       0]
 [      0       0  667395 ...       0       0       0]
 ...
 [      0       0       0 ...       0   13189       0]
 [      0       0       0 ...       0       0   12821]
 [      0       0       0 ...       0       0       0]]
	Ni= [1231237  733772  668333  483957  350599  333594  284232  274600  141089
  118118  190280  120409  153744   99822  117264   99544   98753   83592
   72090   72632   45632   52892   50860   49117   50765   43920   42953
   40489   40028   38438   36058   36303   33885   33381   33716   34044
   30939   32484   31015   31854   31486   28116   27129   26582   28447
   27832   27191   25104   26895   27518   25186   24747   25480   23941
   23996   11592   14834   22509   23221   23494   20127   21752   19084
   21574   19823   19573   20176   19442   18717   18414       0   18675
    8134   17062   13421   17072   168

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
21
[[1057544       0       0 ...       0       0       0]
 [      0  547195       0 ...       0       0       0]
 [      0       0  591741 ...       0       0       0]
 ...
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...       0       0       0]]
	Ni= [1058195  646331  595287  409915  296720  288116  258589  241414  121584
   91210  153556   95670  135281   69235   95489   89503   89524   75010
   65467   56885   36952   40740   44659   43384   49837   37047   37890
   37312   36706   36174   33020   34788   29930   29702   30539   31343
   27832   29375   28285   28767   29099   24677   21579   22386   25290
   25214   23639   20445   24434   27426   22734   22074   22879   20934
   20559    8301   12606   20164   20708   21763   16727   19921   16957
   19821   16982   17005   18636   16685   16914   16594       0   17400
       0   14274    8492   15176   152

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
28
[[1184409       0       0 ...       0       0       0]
 [      0  603218       0 ...       0       0       0]
 [      0       0  644737 ...       0       0       0]
 ...
 [      0       0       0 ...       0   11623       0]
 [      0       0       0 ...       0       0       0]
 [      0       0       0 ...   12847       0       0]]
	Ni= [1184528  606508  644918  447540  308885  287097  299405  257637  111778
  134483  170626  141605  101538   88275  100318  100468   95491   84086
   62914   86562   62836   59783   48272   47283   38118   42782   41488
   40823   38824   38551   37716   36340   35104   34862   30746   32199
   31991   32784   30823   30591   30855   29415   30638   28666   26081
   28849   17168   26796   26506   24145   24244   25121   25116   21899
   25083   24130   23700   21842   23121   19071   22411   21445   20807
   20598   19057   19500   19633   19906   19087   19402   10018   18039
   18129   17510   18114   17514   163

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
28
[[782825      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 [     0 470105      0 ...      0      0      0]
 ...
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]]
	Ni= [792178 387492 472761 336180 208122 225310 214155 184572  60919  93803
 116320 109088  73481  86830  66800  56660  71708  51115  44982  44943
  47885  56743  35035  37638  27407  30420  32289  25483  32073  31872
  31782  31217  24798  28266  23018  25140  24979  25909  24496  22967
  24229  14316  25078  20735  16783  28407      0  19151  14896  15572
  16387  17932  21020  13913  19910  18037  16329  15730  18239      0
  17457  15758  15480  17108   9202      0  12364  19790  12807  16268
   4546  11455  17618  12761  15282  11040  12461  11747  13808  12841
  12730  10982  12580   8337      0  12429   9703  11355      0  10238
  12906      0  104

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
27
[[769632      0      0 ...      0      0      0]
 [     0 478144      0 ...      0      0      0]
 [     0      0 365988 ...      0      0      0]
 ...
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0   8859      0]
 [     0      0      0 ...      0      0      0]]
	Ni= [770398 479555 365988 319383 203510 173129 190409 202002 115446  99795
 114451  60969 115160  74495  74930  74485  70359  47624  50164  47495
  36934  35488      0  34886  36358  27240  33654  32871  32742  31885
  31852  32924  31030  26938  27929  21620  25312  24941  25715  26695
  24650  21581  22932  22974  16502  20545  19939  12607  17696  23367
  22224   5458  22328  19827  18487  17580  18641  17476  17433  17243
  14051      0  14590  16260  15115  15430  15279  10953  15294  13996
  14092  11205  13606  14817  13099  13127  12483  10705  12007  13031
  12510   5542  11820  10876  10363  10410  10868  10593   8051  10395
  10891   9812  109

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
27
[[686691      0      0 ...      0      0      0]
 [     0 445071      0 ...      0      0      0]
 [     0      0 333212 ...      0      0      0]
 ...
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]]
	Ni= [687803 447415 333212 291879 181607 148170 170064 185095  96418  84618
 112446  51591 110258  67985  65618  67810  65872  44684  45711  43428
  29904  31080      0  29549  33823  29504  30684  30817  30852  29986
  29985  32594  29624  24616  26144  19154  23060  22328  23220  24843
  17222  20592  21076  21214  12977  17205  17966  10894  13957  21872
  20808  15096  22153  18118  17099  15928  17082  15867  16252  16346
  11873   8873  13269  15172  13563  14040  14192   9307  14370  10424
  12786   8719  12366  14397  11656  12123  10872   9186  10860  12303
  11435   4348  10977   8656   9412   9814   9655   9723   7238   9044
  10120      0  103

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
21
[[605317      0      0 ...      0      0      0]
 [     0 390600      0 ...      0      0      0]
 [     0      0 263843 ...      0      0      0]
 ...
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]]
	Ni= [615965 414150 290118 235268 152552 139593 177505 153135 124546 130837
  49876  68817  89175  39165  62618  59107  63402  61944  43090  39925
  31624  27750  15678  29956  33369  27687  28043  28517  27083  26888
  23064  17167  22289  23488  18526  24095  20977  23410  19016  20000
  10128  21329  19457  20128  15606  15551  16710  15820  15899  15572
      0  16109  12817  16031  15324  15977  16434  13875  13909  13972
  14234  10312  10167  12599  14013  12767  12213  12111  11107   7248
   9705  11542  10961  11903      0  10446   8424      0   9087   9240
   9579   9001   7073   9510   9019   9301      0   8544   8371   6710
   9450      0   85

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
21
[[569908      0      0 ...      0      0      0]
 [     0 345359      0 ...      0      0      0]
 [     0      0 238719 ...      0      0      0]
 ...
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]]
	Ni= [570739 388313 264456 220346 146936 133209 164313 141846 112988 113732
  33496  61538  82946  34682  51496  58534  57951  57028  39083  37980
  30000  24932  12708  28334  32309  25716  26761  27247  25070  24608
  20485  14667  20928  21243  17138  22830  19846  22680  16756  18743
   8811  20181  18242  19402  15359  13886  15843  14338  14713  14328
   7884  15575  12124  14983  14475  15193  15647  12754  13575  13476
  13538   6997   9036  11549  12931  11510  11143  11185  10661   7228
   8480  10379  10574  11419      0  10145   8884      0   8416   8795
   8847   8574   5679   8647   8204   8636      0   8329   7774      0
   9269      0   78

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
28
[[467961      0      0 ...      0      0      0]
 [     0 227279      0 ...      0      0      0]
 [     0      0 194574 ...      0      0      0]
 ...
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]]
	Ni= [510197 258406 194757 181652 127390 142054  99769 123069  72404  80651
  74341  44529  17603  44868  37276  45179  33905  27871  13185  18221
  28172  24972  26518  10241  25924  22700  25520  20976  13489  19643
  21624  19806  18362   8443  14943  18288  18526  11627  14265  11102
  14625   5848  14634  10147   8975  13887  11770  13246  13398  11689
  10552  12565  12706      0  11230   7693      0   7636  12833  11612
   8303  11728  14394   7752  14544      0   9022   8790   7169  10848
   9347   9749   9656   7411      0   8833  10523   7633      0   6993
   7350      0      0   8673   9469   3886   6143      0   7507   6628
   7021   7284   75

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
28
[[467705      0      0 ...      0      0      0]
 [     0 197794      0 ...      0      0      0]
 [     0      0 188413 ...      0      0      0]
 ...
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]]
	Ni= [507959 239740 188545 172050 123273 138891  97262 109977  65604  74872
  70688  45451  17655  42002  33280  42939  32379  26402  12299  15996
  27002  24238  25420  15719  25126  20264  24534  22484  10488  18506
  20984  18849  17586  12917  13787  18128  17847  12168  13702   8782
  13916   5474  14039   9390   7501  13248  10001  12498  12543  10597
  10001  12188  12302      0  10708   7812      0      0  12492  10806
   6798  11503  14191   6975  14690      0   8532   8623   7113  10695
   9074   9174   9240   6976      0   9123  10266   7138      0      0
   7566      0      0   8472   9311      0   5847      0   7477      0
   7130   6917   74

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
61
[[     0  77261      0 ...      0      0      0]
 [     0      0  89352 ...      0      0      0]
 [111588      0      0 ...      0      0      0]
 ...
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]]
	Ni= [198505  92367 113597  59108  92377  58375  68346  44732  46189  27782
  21993  19934  36507  19862  28421   6452  11376   8069  18813  14974
   3626   5003  15044  19775  15838   5134  16772  14630  13706   7762
  13143  13656  11530  14881  13603  10689     11   4643      0   4417
   6525   7389   9126      0   8989   6820   7494      0   6808   7575
   9366   9063      0   6164   6588   5847      0   5403   7397   8152
      0      0  10139   4154      0   8746   3432      0      0   3875
   5806   4740      0      0   5873   5786   6434   3803      0      0
      0   4127      0      0      0      0   3328   4570   3614      0
      0   5386   40

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
61
[[    0     0     0 ...  1779     0     0]
 [    0     0     0 ...     0     0     0]
 [53394     0     0 ...     0     0     0]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]
	Ni= [52884 35783 59184 46012 42809 25390 31906 17489 21890 10048  5702  5007
 24079  7207 15982  1738  2456  2836 12488 15239     0  2468  7762  8300
 11359     0 11215 12298 13796  4598 10703 12250  9399  4553  4571  8456
     0  3605     0     0     0  3664  5765     0  6858  2740  5910     0
     0  3977  3304  5611     0     0  5607  3445     0  1858  2650  5131
     0     0  2858  2872     0  1850  2360     0     0  2634  5684  3197
     0     0  4762  2707     0     0  2162     0     0  2397     0     0
  1860     0     0  3656     0     0     0  3098     0     0     0  2002
     0     0     0     0]
	Nj= [53394 44907 22700 23570 19766 14212 21890 20979 16402 15239 15748 15062
 13649

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


	Matching halos by merit function
72
[[33200     0     0 ...     0     0     0]
 [    0 16982     0 ...     0     0     0]
 [    0     0 14074 ...     0     0     0]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]
	Ni= [33982 21802 14074 12415  8231  4546 13332  8618 10869     0  4459  5337
  5048  7443  7680  5825  3566  5382  4655  5825  4858  6815     0  1311
  6619  2961  2948  4357  3249  4941  3449     0  2636  1024  3488  3086
  2706     0     0  3873  2928  2864  1263  2981  1956  2897  1544    15
     0  1250  2629  1343  1561  1224     0     0  2051  1248  1675     0
  1227  1166  2056  1142     0   747  1173     0  1036     0  1259  1027
     0     0     0     0     0     0  1189     0     0     0  1199  1120
     0  1263   675     0     0  1041     0  1278  1101   851   919   974
   792  1127     0   428]
	Nj= [33208 16982 14074 13332 10355 10866  7680  7443  6619  6815  5715  8618
  7627

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


[[35918     0     0 ...     0     0     0]
 [    0 13956     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]
	Ni= [36408 17592  7566 10238  4835  2291 10014 10355  9478  2234     0   620
  5923  6336  3894  4723  3571  4511  3551  5073  3287  6038  6562  1587
  6160  2267  1928  2652     0  4842  2333   632  1852  1240  3361  3135
  2297     0     0  4521  1580  1039   860  3111  1113  2240  1181     3
   760   669     0   799  1087   863  1576  1209  1301  1045  1432     0
   780   848     0   863     0   832  1146     0   873     0   620  1062
     3     0     0     0     0     0   899     0     0   563     0   606
     0  1229   649     0     0     0     0     0  1183     0   854   615
     0  1376     0     0]
	Nj= [35929 13956  9477  8441  6562 10355  7566 10014  6160  6336  4521  5321
  6038  5073  4548  4723  4511  3135  3894 

/home/selvani/MAP/pynbody/halo_trace/halo_trace/tracing.py:79: RuntimeWarning: invalid value encountered in divide
  merit_f = mat**2/np.outer(Ni, Nj)


In [5]:
'''# Debug: Check what paths are being constructed
from pathlib import Path
import glob

sim_high_path = '/home/selvani/MAP/Sims/cptmarvel.cosmo25cmb/cptmarvel.cosmo25cmb.4096g5HbwK1BH/cptmarvel.cosmo25cmb.4096g5HbwK1BH.003968/cptmarvel.cosmo25cmb.4096g5HbwK1BH.003968'
pth = Path(sim_high_path)
ahf_dir = 'ahf_200'

print(f"Simulation file path: {pth}")
print(f"Parent directory: {pth.parent}")
print(f"Looking for AHF files in: {pth.parent / ahf_dir}")

# Check what files actually exist
ahf_files = list(pth.parent.glob(f'{ahf_dir}/*AHF_halos'))
print(f"Found AHF files: {ahf_files}")

if ahf_files:
    ahf_basename = str(ahf_files[0])[:-10]  # Remove '.AHF_halos'
    print(f"ahf_basename would be: {ahf_basename}")
    
    # Check what related files exist
    print(f"Checking for related files:")
    print(f"  {ahf_basename}.AHF_halos exists: {Path(ahf_basename + '.AHF_halos').exists()}")
    print(f"  {ahf_basename}.AHF_particles exists: {Path(ahf_basename + '.AHF_particles').exists()}")
'''

'# Debug: Check what paths are being constructed\nfrom pathlib import Path\nimport glob\n\nsim_high_path = \'/home/selvani/MAP/Sims/cptmarvel.cosmo25cmb/cptmarvel.cosmo25cmb.4096g5HbwK1BH/cptmarvel.cosmo25cmb.4096g5HbwK1BH.003968/cptmarvel.cosmo25cmb.4096g5HbwK1BH.003968\'\npth = Path(sim_high_path)\nahf_dir = \'ahf_200\'\n\nprint(f"Simulation file path: {pth}")\nprint(f"Parent directory: {pth.parent}")\nprint(f"Looking for AHF files in: {pth.parent / ahf_dir}")\n\n# Check what files actually exist\nahf_files = list(pth.parent.glob(f\'{ahf_dir}/*AHF_halos\'))\nprint(f"Found AHF files: {ahf_files}")\n\nif ahf_files:\n    ahf_basename = str(ahf_files[0])[:-10]  # Remove \'.AHF_halos\'\n    print(f"ahf_basename would be: {ahf_basename}")\n\n    # Check what related files exist\n    print(f"Checking for related files:")\n    print(f"  {ahf_basename}.AHF_halos exists: {Path(ahf_basename + \'.AHF_halos\').exists()}")\n    print(f"  {ahf_basename}.AHF_particles exists: {Path(ahf_basename + \'

In [6]:
'''import pynbody as pb
s = pb.load(sim_base + 'cptmarvel.cosmo25cmb.4096g5HbwK1BH.004096/cptmarvel.cosmo25cmb.4096g5HbwK1BH.004096')
s.physical_units()

ahf_basename = sim_base + '/cptmarvel.cosmo25cmb.4096g5HbwK1BH.004096/ahf_200/cptmarvel.cosmo25cmb.4096g5HbwK1BH.004096.0000.z0.000.AHF_'
#check if file exists
if not os.path.exists(ahf_basename + 'halos'):
    raise FileNotFoundError(f"AHF halos file does not exist: {ahf_basename}.AHF_halos")
else:
    print(f"AHF halos file found: {ahf_basename}halos")
halos = s.halos(halo_numbers='v1', ahf_basename=ahf_basename)
print(f"Loaded halos: {halos}")'''

'import pynbody as pb\ns = pb.load(sim_base + \'cptmarvel.cosmo25cmb.4096g5HbwK1BH.004096/cptmarvel.cosmo25cmb.4096g5HbwK1BH.004096\')\ns.physical_units()\n\nahf_basename = sim_base + \'/cptmarvel.cosmo25cmb.4096g5HbwK1BH.004096/ahf_200/cptmarvel.cosmo25cmb.4096g5HbwK1BH.004096.0000.z0.000.AHF_\'\n#check if file exists\nif not os.path.exists(ahf_basename + \'halos\'):\n    raise FileNotFoundError(f"AHF halos file does not exist: {ahf_basename}.AHF_halos")\nelse:\n    print(f"AHF halos file found: {ahf_basename}halos")\nhalos = s.halos(halo_numbers=\'v1\', ahf_basename=ahf_basename)\nprint(f"Loaded halos: {halos}")'

In [7]:
'''import pynbody as pb
file = sim_base + '/snapshots_200crit_cptmarvel/cptmarvel.cosmo25cmb.4096g5HbwK1BH.003968/'
s = pb.load(file)
h = s.halos(halo_numbers='v1')
# Check if the halo catalog is loaded correctly
if h is None:
    raise ValueError("Halo catalog could not be loaded. Please check the file path and format.")
# Check the number of halos
num_halos = len(h)
print(f"Number of halos in the catalog: {num_halos}")'''

'import pynbody as pb\nfile = sim_base + \'/snapshots_200crit_cptmarvel/cptmarvel.cosmo25cmb.4096g5HbwK1BH.003968/\'\ns = pb.load(file)\nh = s.halos(halo_numbers=\'v1\')\n# Check if the halo catalog is loaded correctly\nif h is None:\n    raise ValueError("Halo catalog could not be loaded. Please check the file path and format.")\n# Check the number of halos\nnum_halos = len(h)\nprint(f"Number of halos in the catalog: {num_halos}")'

In [8]:
'''import pynbody as pb
s = pb.load(sim_base + 'cptmarvel.cosmo25cmb.4096g5HbwK1BH.003968/cptmarvel.cosmo25cmb.4096g5HbwK1BH.003968')
s.physical_units()

ahf_basename = sim_base + '/cptmarvel.cosmo25cmb.4096g5HbwK1BH.003968/ahf_200/cptmarvel.cosmo25cmb.4096g5HbwK1BH.003968.0000.z0.033.AHF_'
#check if file exists
if not os.path.exists(ahf_basename + 'halos'):
    raise FileNotFoundError(f"AHF halos file does not exist: {ahf_basename}.AHF_halos")
else:
    print(f"AHF halos file found: {ahf_basename}halos")
halos = s.halos(halo_numbers='v1', ahf_basename=ahf_basename)'''

'import pynbody as pb\ns = pb.load(sim_base + \'cptmarvel.cosmo25cmb.4096g5HbwK1BH.003968/cptmarvel.cosmo25cmb.4096g5HbwK1BH.003968\')\ns.physical_units()\n\nahf_basename = sim_base + \'/cptmarvel.cosmo25cmb.4096g5HbwK1BH.003968/ahf_200/cptmarvel.cosmo25cmb.4096g5HbwK1BH.003968.0000.z0.033.AHF_\'\n#check if file exists\nif not os.path.exists(ahf_basename + \'halos\'):\n    raise FileNotFoundError(f"AHF halos file does not exist: {ahf_basename}.AHF_halos")\nelse:\n    print(f"AHF halos file found: {ahf_basename}halos")\nhalos = s.halos(halo_numbers=\'v1\', ahf_basename=ahf_basename)'

## Open Trace

By default, it will save your trace. In my case I've already run this trace, so it will decline to overwrite it. In your case, you'll see information printed to screen as the trace goes on. Since I've already created the trace, I'll go ahead and load it now:

In [8]:
# trace = pd.read_hdf(sim_base + 'h148.cosmo50PLK.6144g3HbwK1BH.004096/h148.cosmo50PLK.6144g3HbwK1BH.004096.trace_back.hdf5')

trace = pd.read_hdf('/home/selvani/MAP/Sims/cptmarvel.cosmo25cmb/cptmarvel.cosmo25cmb.4096g5HbwK1BH/cptmarvel.cosmo25cmb.4096g5HbwK1BH.004096/cptmarvel.cosmo25cmb.4096g5HbwK1BH.004096.trace_back.hdf5')

The index is the present day halo ID. Each column represents the main progenitor of a halo at that timestep:

In [13]:
trace

003968  003840  003712  003636  003584  003456  003328  003245  \
004096                                                                     
0040961        1       1       1       1       1       1       1       1   
0040962        2       2       2       2       2       2       2       2   
0040963        3       3       3       3       3       3       3       3   
0040965        5       5       5       5       5       5       5       5   
0040966        6       6       6       6       6       6       6       6   
0040967        7       7       7       7       7       7       7       7   
0040968        8       8       9       9       9       9       9       9   
00409610      10      10      10      10      10      10      10      10   
00409611      11      11      11      11      11      11      11      11   
00409613      13      13      13      13      13      13      13      13   
00409616      16      16      16      16      16      16      16      16   

          003200  003072  ...  000818  000768  000672  000640  000512  000482  \
004096                    ...                                                   
0040961        1       1  ...       1       1       1       1       1       1   
0040962        2       2  ...       4       4       4       4       4       4   
0040963        3       3  ...       6       6       5       7       8       7   
0040965        5       5  ...       2       2       2       2       2       2   
0040966        6       6  ...       3       3       3       3       3       3   
0040967        7       7  ...       8       8       8       8       7       8   
0040968        9       9  ...      13      11      12      13      48      41   
00409610      10      10  ...       7       7       7       6       5       5   
00409611      11      11  ...      11      13      11      11      10       9   
00409613      13      13  ...      10       9       9       9       9      10   
00409616      17      16  ...      16      14      18      19      17      18   

          000291  000199  000146  000128  
004096                                    
0040961        2      42      49       3  
0040962        9       2       2       2  
0040963        4       3       3       7  
0040965        3       5      13      27  
0040966        1       1       1       1  
0040967       13      12      18      93  
0040968       61      -1      -1      -1  
00409610       5       6      31      28  
00409611      10       7       4       8  
00409613      14      48      -1      -1  
00409616      19      32      -1      44  

[11 rows x 42 columns]

If you don't know how to use pandas, this might take a bit to get used to. To see the main progenitor IDs of halo 7, for example, you do this:

In [14]:
trace.loc['0040961']

003968     1
003840     1
003712     1
003636     1
003584     1
003456     1
003328     1
003245     1
003200     1
003072     1
002944     1
002816     1
002688     1
002624     1
002560     1
002432     1
002304     1
002176     1
002162     1
002048     1
001920     1
001813     1
001792     1
001664     1
001543     1
001536     1
001408     1
001331     1
001280     1
001162     1
001152     1
000896     1
000818     1
000768     1
000672     1
000640     1
000512     1
000482     1
000291     2
000199    42
000146    49
000128     3
Name: 0040961, dtype: int64

To see the main progenitor ID just at step 000188, for example, you would do this:

In [ ]:
# Fix the index by removing the '004096' prefix
trace.index = trace.index.str.replace('004096', '')

# Convert to integers if desired
trace.index = trace.index.astype(int)

In [19]:
trace.to_hdf('/home/selvani/MAP/pynbody/cptmarvel.cosmo25cmb.4096g5HbwK1BH.004096.trace_back.hdf5', key='ids')

## Analyze

In [22]:
trace = pd.read_hdf('/home/selvani/MAP/pynbody/cptmarvel.cosmo25cmb.4096g5HbwK1BH.004096.trace_back.hdf5', key='ids')

In [23]:
trace.loc[7, '003840']

np.int64(7)

or for several steps:

In [24]:
trace.loc[7, ['000199', '000640']]

000199    12
000640     8
Name: 7, dtype: int64

The -1s (and, in some cases, NaNs) represent steps where the main progenitor could not be idenified. Most larger halos are traced back pretty far. here is an example of a halo that wasn't:

In [25]:
trace.loc[16]

003968    16
003840    16
003712    16
003636    16
003584    16
003456    16
003328    16
003245    16
003200    17
003072    16
002944    14
002816    14
002688    14
002624    14
002560    14
002432    14
002304    13
002176    14
002162    14
002048    13
001920    13
001813    14
001792    14
001664    13
001543    14
001536    14
001408    14
001331    14
001280    14
001162    19
001152    20
000896    18
000818    16
000768    14
000672    18
000640    19
000512    17
000482    18
000291    19
000199    32
000146    -1
000128    44
Name: 16, dtype: int64

## Do I Need This?

Using the identified halos from the trace, you can read in any value in the amiga.stat or AHF_halos files and put it in a DataFrame of its own. Every time you read in an amiga.stat file you'll get some output information; this mainly has to do with connecting AHF files to amiga files, and you should be able to ignore it.

In [21]:
mvir_trace, rvir_trace, distance = ht.tracing.trace_quantity(sim_base, trace_df=trace, 
                                       quantity=['Mvir(M_sol)', 'Rvir(kpc)', 'Nearest'])

/home/selvani/MAP/Sims/cptmarvel.cosmo25cmb/cptmarvel.cosmo25cmb.4096g5HbwK1BH/cptmarvel.cosmo25cmb.4096g5HbwK1BH.004096/cptmarvel.cosmo25cmb.4096g5HbwK1BH.004096 



/home/selvani/MAP/pynbody/halo_trace/halo_trace/amiga_ahf.py:149: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(amiga_file,


Rvir is within 0.01%! Match confirmed.


TypeError: loop of ufunc does not support argument 0 of type numpy.float64 which has no callable sqrt method

Again, if you don't know pandas, this might take a bit to get used to. The maximum halo mass reached by every halo throughout its history (at least, its successfully traced history) can be found in one step:

In [10]:
mvir_trace.max(axis=1)

Grp
1        2.402080e+12
2        1.327024e+11
3        6.989641e+10
4        3.851439e+10
5        4.217958e+10
             ...     
15289    2.986070e+06
15291    1.913236e+06
15292    2.574561e+06
15293    2.824864e+06
15294    3.182441e+06
Length: 11356, dtype: float64

In [11]:
mvir_trace.idxmax(axis=1)

Grp
1        004096
2        003360
3        002555
4        002592
5        002880
          ...  
15289    002400
15291    003072
15292    001024
15293    001920
15294    001664
Length: 11356, dtype: object

Or, the mass at z=6 (step 275 in this simulation):

In [12]:
mvir_trace['000275']

Grp
1        2.863878e+08
2        2.216010e+09
3        3.669721e+09
4        7.197241e+09
5        1.117208e+09
             ...     
15289             NaN
15291             NaN
15292             NaN
15293             NaN
15294             NaN
Name: 000275, Length: 11356, dtype: float64

## Troubleshooting

If you're encountering errors related to the AHF or amiga files, it's possible there are multiple versions of the AHF catalogs laying around in the directory. Make sure there is one set of AHF files, and that the amiga files correspond to that run of AHF.